module.exports = {
	addressesEndPoint: 'addresses/',
	requestOtpEndPoint: 'request-otp/',
	verifyOtpEndPoint: 'verify-otp/',
	registerEndPoint: 'register/',
	getPrintConfigEndPoint: 'configurations/',
	orderEndPoint: 'orders/',
	getSubscriptionPlansEndPoint: 'subscription-plans/',
	buySubscriptionEndPoint: 'user-subscription-plans/',
	verifySubscriptionPayment: 'verify-subscription-payment/',
	getDependentConfigs: 'get-dependent-configs/',
	uploadPDFEndPoint: 'order-files/',
	getDeliveryChargesEndPoint: 'get-delivery-charges/',
	verifyPaymentEndPoint: 'verify-payment/',
	getHaveSubscriptions: 'have-subscription/',
	usersEndpoint: 'users/',
	totalPrintedEndpoint: 'user-total-prints/',
	sendEmailVerification: 'send-email-for-verification/',
};
